// Code generated by protoc-gen-go.
// source: rank.proto
// DO NOT EDIT!

/*
Package serverproto is a generated protocol buffer package.

It is generated from these files:
	rank.proto

It has these top-level messages:
	RankUnit
	ServerTimeRange
	GetRequest
	GetResponse
	GetByRankRequest
	GetByRankResponse
	GetRangeRequest
	GetRangeResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
*/
package serverproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MessageType int32

const (
	MessageType_TypeGetRequest        MessageType = 10000
	MessageType_TypeGetResponse       MessageType = 10001
	MessageType_TypeGetByRankRequest  MessageType = 10002
	MessageType_TypeGetByRankResponse MessageType = 10003
	MessageType_TypeGetRangeRequest   MessageType = 10004
	MessageType_TypeGetRangeResponse  MessageType = 10005
	MessageType_TypeUpdateRequest     MessageType = 10006
	MessageType_TypeUpdateResponse    MessageType = 10007
	MessageType_TypeDeleteRequest     MessageType = 10008
	MessageType_TypeDeleteResponse    MessageType = 10009
)

var MessageType_name = map[int32]string{
	10000: "TypeGetRequest",
	10001: "TypeGetResponse",
	10002: "TypeGetByRankRequest",
	10003: "TypeGetByRankResponse",
	10004: "TypeGetRangeRequest",
	10005: "TypeGetRangeResponse",
	10006: "TypeUpdateRequest",
	10007: "TypeUpdateResponse",
	10008: "TypeDeleteRequest",
	10009: "TypeDeleteResponse",
}
var MessageType_value = map[string]int32{
	"TypeGetRequest":        10000,
	"TypeGetResponse":       10001,
	"TypeGetByRankRequest":  10002,
	"TypeGetByRankResponse": 10003,
	"TypeGetRangeRequest":   10004,
	"TypeGetRangeResponse":  10005,
	"TypeUpdateRequest":     10006,
	"TypeUpdateResponse":    10007,
	"TypeDeleteRequest":     10008,
	"TypeDeleteResponse":    10009,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RankUnit struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Key              *uint64 `protobuf:"varint,2,opt,name=key" json:"key,omitempty"`
	Value            []byte  `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RankUnit) Reset()                    { *m = RankUnit{} }
func (m *RankUnit) String() string            { return proto.CompactTextString(m) }
func (*RankUnit) ProtoMessage()               {}
func (*RankUnit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RankUnit) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RankUnit) GetKey() uint64 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *RankUnit) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ServerTimeRange struct {
	Begin            *int64 `protobuf:"varint,1,opt,name=begin" json:"begin,omitempty"`
	End              *int64 `protobuf:"varint,2,opt,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ServerTimeRange) Reset()                    { *m = ServerTimeRange{} }
func (m *ServerTimeRange) String() string            { return proto.CompactTextString(m) }
func (*ServerTimeRange) ProtoMessage()               {}
func (*ServerTimeRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServerTimeRange) GetBegin() int64 {
	if m != nil && m.Begin != nil {
		return *m.Begin
	}
	return 0
}

func (m *ServerTimeRange) GetEnd() int64 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

type GetRequest struct {
	// 操作的排行榜ID
	Rank *uint32 `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	// 查询的数据ID
	Id               *uint64 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetRequest) GetRank() uint32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *GetRequest) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type GetResponse struct {
	// 操作的排行榜ID
	Rank *uint32 `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	// 查询的数据排名, 0表示未上榜
	Pos *uint32 `protobuf:"varint,2,opt,name=pos" json:"pos,omitempty"`
	// 查询的数据
	Data             *RankUnit `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetResponse) GetRank() uint32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *GetResponse) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *GetResponse) GetData() *RankUnit {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetByRankRequest struct {
	// 操作的排行榜ID
	Rank *uint32 `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	// 查询的数据排名
	Pos              *uint32 `protobuf:"varint,2,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetByRankRequest) Reset()                    { *m = GetByRankRequest{} }
func (m *GetByRankRequest) String() string            { return proto.CompactTextString(m) }
func (*GetByRankRequest) ProtoMessage()               {}
func (*GetByRankRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetByRankRequest) GetRank() uint32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *GetByRankRequest) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type GetByRankResponse struct {
	// 操作的排行榜ID
	Rank *uint32 `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	// 查询的数据排名, 0表示未上榜
	Pos *uint32 `protobuf:"varint,2,opt,name=pos" json:"pos,omitempty"`
	// 查询的数据
	Data             *RankUnit `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GetByRankResponse) Reset()                    { *m = GetByRankResponse{} }
func (m *GetByRankResponse) String() string            { return proto.CompactTextString(m) }
func (*GetByRankResponse) ProtoMessage()               {}
func (*GetByRankResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetByRankResponse) GetRank() uint32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *GetByRankResponse) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *GetByRankResponse) GetData() *RankUnit {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetRangeRequest struct {
	// 操作的排行榜ID
	Rank *uint32 `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	// 起始的数据排名
	Start *uint32 `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	// 查询的数据量
	Num              *uint32 `protobuf:"varint,3,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRangeRequest) Reset()                    { *m = GetRangeRequest{} }
func (m *GetRangeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRangeRequest) ProtoMessage()               {}
func (*GetRangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetRangeRequest) GetRank() uint32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *GetRangeRequest) GetStart() uint32 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *GetRangeRequest) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type GetRangeResponse struct {
	// 操作的排行榜ID
	Rank *uint32 `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	// 查询的排行榜数据总量
	Total *uint32 `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	// 查询的数据
	Data             []*RankUnit `protobuf:"bytes,3,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GetRangeResponse) Reset()                    { *m = GetRangeResponse{} }
func (m *GetRangeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRangeResponse) ProtoMessage()               {}
func (*GetRangeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetRangeResponse) GetRank() uint32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *GetRangeResponse) GetTotal() uint32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func (m *GetRangeResponse) GetData() []*RankUnit {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateRequest struct {
	// 操作的排行榜ID
	Rank *uint32 `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	// 上报的数据
	Data *RankUnit `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	// 是否需要返回上报结果
	Reply *bool `protobuf:"varint,3,opt,name=reply" json:"reply,omitempty"`
	// 是否需要返回本次上报之前对应的数据
	LastData *bool `protobuf:"varint,4,opt,name=last_data" json:"last_data,omitempty"`
	// 是否跳过非上报时段校验
	BypassNoUpdate *bool `protobuf:"varint,5,opt,name=bypass_no_update" json:"bypass_no_update,omitempty"`
	// 更新需要满足的服务器时间范围
	ServerTimeRange  *ServerTimeRange `protobuf:"bytes,6,opt,name=server_time_range" json:"server_time_range,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateRequest) GetRank() uint32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *UpdateRequest) GetData() *RankUnit {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateRequest) GetReply() bool {
	if m != nil && m.Reply != nil {
		return *m.Reply
	}
	return false
}

func (m *UpdateRequest) GetLastData() bool {
	if m != nil && m.LastData != nil {
		return *m.LastData
	}
	return false
}

func (m *UpdateRequest) GetBypassNoUpdate() bool {
	if m != nil && m.BypassNoUpdate != nil {
		return *m.BypassNoUpdate
	}
	return false
}

func (m *UpdateRequest) GetServerTimeRange() *ServerTimeRange {
	if m != nil {
		return m.ServerTimeRange
	}
	return nil
}

type UpdateResponse struct {
	// 操作的排行榜ID
	Rank *uint32 `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	// 操作前的排名, 0表示未上榜
	LastPos *uint32 `protobuf:"varint,2,opt,name=last_pos" json:"last_pos,omitempty"`
	// 操作后的排名, 0表示未上榜
	Pos *uint32 `protobuf:"varint,3,opt,name=pos" json:"pos,omitempty"`
	// 操作前对应的数据
	Data             *RankUnit `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateResponse) GetRank() uint32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *UpdateResponse) GetLastPos() uint32 {
	if m != nil && m.LastPos != nil {
		return *m.LastPos
	}
	return 0
}

func (m *UpdateResponse) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *UpdateResponse) GetData() *RankUnit {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteRequest struct {
	// 操作的排行榜ID
	Rank *uint32 `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	// 操作数据的ID
	Id *uint64 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	// 是否需要返回删除结果
	Reply *bool `protobuf:"varint,3,opt,name=reply" json:"reply,omitempty"`
	// 是否需要返回本次删除之前对应的数据
	LastData         *bool  `protobuf:"varint,4,opt,name=last_data" json:"last_data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteRequest) GetRank() uint32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *DeleteRequest) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DeleteRequest) GetReply() bool {
	if m != nil && m.Reply != nil {
		return *m.Reply
	}
	return false
}

func (m *DeleteRequest) GetLastData() bool {
	if m != nil && m.LastData != nil {
		return *m.LastData
	}
	return false
}

type DeleteResponse struct {
	// 操作的排行榜ID
	Rank *uint32 `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	// 操作前的排名, 0表示未上榜
	LastPos *uint32 `protobuf:"varint,2,opt,name=last_pos" json:"last_pos,omitempty"`
	// 操作前对应的数据
	Data             *RankUnit `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeleteResponse) GetRank() uint32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *DeleteResponse) GetLastPos() uint32 {
	if m != nil && m.LastPos != nil {
		return *m.LastPos
	}
	return 0
}

func (m *DeleteResponse) GetData() *RankUnit {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RankUnit)(nil), "serverproto.RankUnit")
	proto.RegisterType((*ServerTimeRange)(nil), "serverproto.ServerTimeRange")
	proto.RegisterType((*GetRequest)(nil), "serverproto.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "serverproto.GetResponse")
	proto.RegisterType((*GetByRankRequest)(nil), "serverproto.GetByRankRequest")
	proto.RegisterType((*GetByRankResponse)(nil), "serverproto.GetByRankResponse")
	proto.RegisterType((*GetRangeRequest)(nil), "serverproto.GetRangeRequest")
	proto.RegisterType((*GetRangeResponse)(nil), "serverproto.GetRangeResponse")
	proto.RegisterType((*UpdateRequest)(nil), "serverproto.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "serverproto.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "serverproto.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "serverproto.DeleteResponse")
	proto.RegisterEnum("serverproto.MessageType", MessageType_name, MessageType_value)
}

var fileDescriptor0 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x53, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0x56, 0x62, 0x17, 0x85, 0x71, 0x9d, 0x6c, 0xb6, 0x2d, 0x18, 0xc4, 0x01, 0x2d, 0x12, 0x42,
	0x48, 0xe4, 0xd0, 0x0b, 0x07, 0x6e, 0x08, 0x89, 0x03, 0xaa, 0x0f, 0x6d, 0x72, 0xb6, 0x36, 0xca,
	0x28, 0xb2, 0xea, 0xda, 0xc6, 0xbb, 0xae, 0xe4, 0x3f, 0xc0, 0x99, 0xf7, 0xe3, 0x97, 0xf0, 0xf7,
	0xd8, 0x9d, 0xda, 0xa9, 0x1d, 0x9c, 0xd2, 0x03, 0x27, 0x6b, 0x67, 0xe6, 0x7b, 0xcc, 0xc3, 0x00,
	0x85, 0x4c, 0xcf, 0x67, 0x79, 0x91, 0xe9, 0x8c, 0x7b, 0x0a, 0x8b, 0x4b, 0x2c, 0xe8, 0x21, 0x8e,
	0x61, 0x74, 0x6a, 0x52, 0x8b, 0x34, 0xd6, 0x1c, 0x60, 0x18, 0xaf, 0x82, 0xc1, 0xe3, 0xc1, 0x33,
	0x97, 0x7b, 0xe0, 0x9c, 0x63, 0x15, 0x0c, 0xe9, 0xe1, 0xc3, 0xde, 0xa5, 0x4c, 0x4a, 0x0c, 0x1c,
	0xf3, 0xdc, 0x17, 0x2f, 0x60, 0x72, 0x46, 0x14, 0xf3, 0xf8, 0x02, 0x0d, 0x7a, 0x8d, 0xb6, 0x62,
	0x89, 0xeb, 0x38, 0x25, 0xb4, 0x63, 0xd1, 0x98, 0xae, 0x08, 0xed, 0x88, 0xa7, 0x00, 0x6f, 0x51,
	0x9f, 0xe2, 0xfb, 0x12, 0x95, 0xe6, 0xfb, 0xe0, 0x5a, 0x2f, 0x54, 0xe8, 0xd7, 0x92, 0xa4, 0x22,
	0x4e, 0xc0, 0xa3, 0x3a, 0x95, 0x67, 0xa9, 0xc2, 0xad, 0x42, 0xc3, 0x98, 0x67, 0x8a, 0x2a, 0x7d,
	0xfe, 0x04, 0xdc, 0x95, 0xd4, 0x92, 0xec, 0x78, 0xc7, 0x47, 0xb3, 0x56, 0x43, 0xb3, 0xa6, 0x1b,
	0xe3, 0x92, 0x19, 0xba, 0xd7, 0x95, 0x0d, 0xf4, 0x8b, 0xb7, 0x39, 0xc5, 0x19, 0x4c, 0x5b, 0xe5,
	0xff, 0xc9, 0xc3, 0x2b, 0x98, 0xd8, 0x96, 0xec, 0x88, 0xfa, 0x2d, 0x98, 0xb9, 0x29, 0x2d, 0x0b,
	0x5d, 0x93, 0x1a, 0x85, 0xb4, 0xbc, 0x20, 0x4e, 0x5f, 0xcc, 0xa9, 0x81, 0x1a, 0xdc, 0x6b, 0xc8,
	0xa0, 0x75, 0xa6, 0x65, 0xf2, 0x97, 0x25, 0x67, 0xb7, 0xa5, 0xdf, 0x03, 0xf0, 0x17, 0xb9, 0xa9,
	0xdb, 0xe1, 0xa8, 0x21, 0x19, 0xde, 0xd0, 0x97, 0x15, 0x2e, 0x30, 0x4f, 0x2a, 0x72, 0x3a, 0xe2,
	0x53, 0xb8, 0x9b, 0x48, 0xa5, 0x23, 0x02, 0xba, 0x14, 0x0a, 0x80, 0x2d, 0xab, 0x5c, 0x2a, 0x15,
	0xa5, 0x59, 0x54, 0x92, 0x5e, 0xb0, 0x47, 0x99, 0x97, 0x30, 0xbd, 0xe2, 0x8c, 0xb4, 0x39, 0x9f,
	0xa8, 0xb0, 0xfd, 0x05, 0x77, 0x48, 0xed, 0x51, 0x47, 0x6d, 0xeb, 0xc6, 0xc4, 0x12, 0xc6, 0x8d,
	0xf1, 0xde, 0x69, 0x30, 0x18, 0x91, 0x8b, 0xeb, 0x1d, 0xd5, 0x0b, 0x73, 0x3a, 0x8d, 0xb9, 0x37,
	0x2d, 0xec, 0x1d, 0xf8, 0x6f, 0x30, 0xc1, 0x5d, 0xc3, 0x69, 0x9d, 0xeb, 0xbf, 0x67, 0x20, 0x16,
	0x30, 0x6e, 0xc8, 0x6e, 0x69, 0xf8, 0x36, 0x47, 0xf5, 0xfc, 0xc3, 0x10, 0xbc, 0x13, 0x54, 0x4a,
	0xae, 0x71, 0x5e, 0xe5, 0xc8, 0x0f, 0x60, 0x6c, 0xbf, 0xd7, 0xff, 0x18, 0xfb, 0x18, 0xf2, 0x43,
	0x98, 0x6c, 0x82, 0x57, 0xe2, 0xec, 0x53, 0xc8, 0x1f, 0xc0, 0x61, 0x1d, 0xed, 0xfc, 0x17, 0xec,
	0x73, 0xc8, 0x1f, 0xc2, 0xd1, 0x56, 0xaa, 0x86, 0x7d, 0x09, 0xcd, 0x32, 0x0f, 0x1a, 0xb2, 0xd6,
	0x29, 0xb3, 0xaf, 0x6d, 0xc2, 0xce, 0x9d, 0xb2, 0x6f, 0x21, 0xbf, 0x07, 0x53, 0x9b, 0xea, 0xdc,
	0x1a, 0xfb, 0x1e, 0xf2, 0xfb, 0xc0, 0xdb, 0xf1, 0x1a, 0xf0, 0x63, 0x03, 0xe8, 0xcc, 0x9f, 0xfd,
	0xdc, 0x00, 0xba, 0xa3, 0x64, 0xbf, 0xc2, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x98, 0xac, 0xe8,
	0x60, 0xd5, 0x04, 0x00, 0x00,
}
